name: gtk_flutter
description: Get to know Firebase with Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.12
  flutter:
    sdk: flutter
  flutter_profile_picture: ^1.0.2
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.4
  image_picker: ^0.8.5
  provider: ^6.0.2
  xfile: ^1.1.0
  http: ^0.13.0+2
  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png
